/* eslint-disable import/prefer-default-export */
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_CORRECTO = 'AGREGAR_PRODUCTO_CORRECTO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

//
export const COMENZAR_DESCARGAR_PRODUCTOS = 'COMENZAR_DESCARGAR_PRODUCTOS';
export const DESCARGAR_PRODUCTOS_EXITO = 'DESCARGAR_PRODUCTOS_EXITO';
export const DESCARGAR_PRODUCTOS_ERROR = 'DESCARGAR_PRODUCTOS_ERROR';
export const TEST = 'TEST';
//

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_CORRECTO = 'PRODUCTO_ELIMINADO_CORRECTO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';
//
export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const COMENZAR_PRODUCTO_EDITAR = 'COMENZAR_PRODUCTO_EDITAR';
export const PRODUCTO_EDITAR_CORRECTO = 'PRODUCTO_EDITAR_CORRECTO';
export const PRODUCTO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR';
//
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
